#!/bin/bash

selected=$(ps -eo pid,user,%cpu,%mem,comm,args --sort=-%cpu | \
      tail -n +2 | \
      fzf --multi --layout=reverse --height=100% \
      --no-scrollbar --info=hidden --no-separator \
      --border=rounded \
      --bind 'tab:toggle' \
      --bind 'shift-tab:toggle+up' \
      --prompt='tab:select|enter:kill> ' | \
  awk '{print $1}' | tr '\n' ' ')

if [ -n "$selected" ]; then
    echo "Selected PIDs: $selected"
    read -r -p "Kill all selected processes? [Y/n] " -e answer
    answer="${answer:-Y}"
    if [[ "$answer" =~ ^[Yy]$ || "$answer" == "" ]]; then
        murder $selected
    fi
fi
